"""initial migration

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-16 08:56:24.093585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_cache",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("service_code", sa.String(32), nullable=False),
        sa.Column("sku_key", sa.String(255), nullable=False),
        sa.Column("region", sa.String(32), nullable=False),
        sa.Column("price_per_unit_usd", sa.Numeric(14, 6), nullable=True),
        sa.Column("unit", sa.String(32), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_unique_constraint("uq_pricing_cache_key", "pricing_cache", ["service_code", "sku_key", "region"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_cache')
    # ### end Alembic commands ###